apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-config
spec:
  applicationSourceSelector:
    matchLabels:
      codefresh.io/product: orders
  priority: 0
  versionSource:
    file: chart.yaml
    jsonPath: $.appVersion
  promotion:
    - Chart.yaml:
      jsonPaths:
        - $.appVersion
    - values.yaml:
      jsonPaths:
        - $.loans.image.tag
