apiVersion: csdp.codefresh.io/v1
kind: ApplicationConfiguration
metadata:
  name: promotion-config
spec:
  applicationSourceSelector:
    matchExpressions:
    - key: app\u002ekubernetes\u002eio/instance
      operator: Exists
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: $.appVersion
  promotion:
    Chart.yaml:
      jsonPaths:
        - $.appVersion
    values.yaml:
      jsonPaths:
        - $.buslog.image.tag
        - $.ctrlr.image.tag
        - $.flask-ui.image.tag
